twitter_consumer_key: EXAMPLE
twitter_consumer_secret: EXAMPLE
twitter_oauth_token: EXAMPLE
twitter_oauth_token_secret: EXAMPLE
notice_queue_uri: tcp://127.0.0.1:6001
message_media_username: EXAMPLE
message_media_password: EXAMPLE
twitter_consumer_key: EXAMPLE
twitter_consumer_secret: EXAMPLE
twitter_oauth_token: EXAMPLE
twitter_oauth_token_secret: EXAMPLE
email_settings:
  address: smtp.sendgrid.net
  port: 587
  domain: stillalive.com
  authentication: plain
  user_name: USERNAME
  password: PASSWORD
  enable_starttls_auto: true
email_from_domain: stillalive.com